---
# The main openstack site deployment playbook

- hosts: all
  roles:
   - huit-accessible
   - common
   - networking-setup
   - pre-tweaks

- hosts: gluster_nodes
  roles: [gluster]

- hosts: gluster_master
  roles: [gluster-master]

- hosts: openstack_compute
  roles: [gluster-client]

- hosts: swift_storage_nodes
  roles: [gluster-client]

- hosts: openstack_controller
  roles:
   - packstack
#   - controller  # don't use this ...

- hosts: openstack_neutron_l3
  roles:
   - network-gateway

- hosts: openstack_neutron_l3
  roles:
   - network-extras

- hosts: openstack_neutron
  roles:
   - network-server-extras

- hosts: openstack_horizon
  roles:
   - network-extras-gui

- hosts: openstack_glance
#  roles: [glance]

- hosts: openstack_compute
  roles:
#   - compute

#- hosts: openstack_glance
#  roles: [glance]

- hosts: openstack_controller
  roles:
   - post-config
#   - testing
