---
# The main openstack site deployment playbook

- hosts: all
  roles:
   - huit-accessible
   - common
   - networking-setup
   - pre-tweaks

- hosts: gluster_nodes
  roles: [gluster]

- hosts: gluster_master
  roles: [gluster-master]

- hosts: openstack_compute
  roles: [gluster-client]

#- hosts: swift_storage_nodes
#  roles: [gluster-client]

- hosts: openstack_controller
  roles:
   - packstack

#
# This is a temp hack unti upstream code is fixed.
#
- hosts: [openstack_compute, openstack_controller, openstack_neutron_l3]
  roles: [ vxlan-fix ]

- hosts: openstack_neutron_l3
  roles:
   - network-extras

- hosts: openstack_neutron
  roles:
   - network-server-extras

- hosts: openstack_horizon
  roles:
   - network-extras-gui

- hosts: openstack_controller
  roles:
#   - trove
#   - sahara

- hosts: openstack_controller
  roles:
   - post-config
#   - testing
