---
# The main openstack site deployment playbook

- hosts: all
  roles:
   - huit-accessible
   - common

- hosts: openstack_controller
  roles:
   - packstack
   - post-config
#   - controller

- hosts: openstack_compute
  roles:
#   - compute
 
#- hosts: gluster_nodes
#  roles:
#   - gluster
