---
# The main openstack site deployment playbook

- hosts: all
  roles:
   - huit-accessible
   - common

- hosts: gluster_nodes
#  roles: [gluster]

- hosts: gluster_master
#  roles: [gluster-master]

- hosts: openstack_compute
#  roles: [gluster-client]

- hosts: swift_storage_nodes
#  roles: [gluster-client]

- hosts: openstack_controller
  roles:
  - packstack
#   - controller  # don't use this ...

- hosts: openstack_compute
  roles:
#   - compute

- hosts: testing
  roles:
  - testing

#- hosts: openstack_glance
#  roles: [glance]

- hosts: openstack_controller
  roles:
   - post-config