---
# The main openstack site deployment playbook

- hosts: all
  roles:
   - accessible
   - common

- hosts: openstack_controller
  roles:
   - controller

- hosts: openstack_compute
  roles:
   - compute
 
 
