# http://docs.openstack.org/developer/trove/dev/manual_install.html

- name: install trove packages 
  yum: name={{ item }} state=present
  environment: proxy_env
  with_items:
   - python-trove
   - openstack-trove
   - openstack-trove-common
   - openstack-trove-api
   - openstack-trove-taskmanager
   - openstack-trove-conductor

#
# Read admin credentials
#
- name: read in admin password
  shell: grep OS_PASSWORD /root/keystonerc_admin | awk -F= '{ print $2 }'
  register: admin_pass

- name: read in admin password
  shell: grep OS_AUTH_URL /root/keystonerc_admin | awk -F= '{ print $2 }'
  register: auth_url  

- name: read in admin token
  shell: grep "^admin_token" /etc/keystone/keystone.conf | awk -F= '{ print $2 }' | sed 's/ //'
  register: admin_token 

- name: read in IP used for services
  shell: "keystone --os-token {{ admin_token.stdout }} endpoint-list | grep :8774/ | awk -F/ '{print $3}' |awk -F: '{print $1}'"
  register: endpoint_ip

#
# Create trove objects in keystone
#
- name: Create trove tenant
  keystone_user: token={{ admin_token.stdout }} tenant=trove tenant_description="Trove"
  register: tenant

- name: Create trove user
  keystone_user: token={{ admin_token.stdout }} user=trove tenant=trove password={{ admin_pass.stdout }}

- name: give trove user admin rights  
  shell: keystone --os-token {{ admin_token.stdout }} --os-auth-url http://127.0.0.1:35357/v2.0 user-role-add --user trove --tenant trove --role admin

- name: create service account
  shell: keystone --os-token {{ admin_token.stdout }}  --os-tenant-name admin --os-auth-url http://127.0.0.1:35357/v2.0 service-create --name trove --type database

- name: create endpoint entries for trove
  shell: keystone --os-token {{ admin_token.stdout }}  --os-tenant-name admin --os-auth-url http://127.0.0.1:35357/v2.0 endpoint-create --service trove --region RegionOne --publicurl 'http://{{ endpoint_ip.stdout }}:8779/v1.0/$(tenant_id)s' --adminurl 'http://{{ endpoint_ip.stdout }}:8779/v1.0/$(tenant_id)s' --internalurl 'http://{{ endpoint_ip.stdout }}:8779/v1.0/$(tenant_id)s'
