---
# Run packstack

- name: install needed packages for packstack to operate
  yum: name={{ item }} state=present
  with_items:
   - openstack-packstack 
       
- name: Create packstack answers file
  template: src=packstack-answers.txt.j2 dest=/tmp/packstack-answers.txt
  
- name: Now run packstack ...
  shell: packstack --answer-file=/tmp/packstack-answers.txt >> /tmp/packstack.log
  
