---
# Run packstack

- name: install needed packages for packstack to operate
  yum: name={{ item }} state=present
  environment: proxy_env
  with_items:
   - openstack-packstack 
   - mod_ssl
   - sheepdog

- name: install packages that packstack missed
  yum: name={{ item }} state=present
  environment: proxy_env
  with_items:
   - python-jsonpatch
   - python-jsonpointer
   - python-openstackclient

- name: ensure the latest of some packages for packstack
  yum: name={{ item }} state=latest
  environment: proxy_env
  with_items:
   - python-migrate

- name: Copy over packstack passwords helper script
  copy: src=create-packstack-passwords.sh dest=/tmp/create-packstack-passwords.sh mode=0775

- name: Create a packstack passwords answer file
  shell: creates=/tmp/packstack-passwords.txt  /tmp/create-packstack-passwords.sh

- name: Create packstack answers file
  template: src=packstack-answers.txt.j2 dest=/tmp/packstack-answers.txt

- name: Append passwords to packstack answers file  
  shell: cat /tmp/packstack-passwords.txt  >> /tmp/packstack-answers.txt

- name: Duplicate the NEUTRON -> QUANTUM settings for grizzly vs. havana
  shell: grep NEUTRON /tmp/packstack-answers.txt | sed 's/_NEUTRON_/_QUANTUM_/g' >> /tmp/packstack-answers.txt

- name: setup ssh keys for root
  shell: cd /root/.ssh && rm -f id_rsa* && ssh-keygen -f id_rsa -t rsa -N '' && cat id_rsa.pub >> authorized_keys

- name: Now run packstack ...
  shell: /usr/bin/packstack --answer-file=/tmp/packstack-answers.txt >> /tmp/packstack.log
  environment: proxy_env
  async: 3600
  poll: 10

- name: Retrieve the installed credentials for admin
  fetch: src=keystonerc_admin dest=keystonerc_admin flat=yes

- name: Install some extra OpenStack bit and pieces
  yum: name={{ item }} state=present
  environment: proxy_env
  with_items:
   - openstack-neutron-vpn-agent
   - openstack-savanna

- name: Fix permissions for nova if using a gluster mount
  shell: "[ -d /mnt/gv-instances ] && chown -R nova.nova /mnt/gv-instances"
  ignore_errors: yes

- name: Fix permissions for cinder if using a gluster mount
  shell: "[ -d /mnt/gv-cinder ] && chown -R cinder.cinder /mnt/gv-cinder"
  ignore_errors: yes
