---

# The common tasks

- name: ec2 facts
  ec2_facts:

- name: avoid an update to cloud-init that might break access
  lineinfile: dest=/etc/yum.conf
              regexp="^exclude=cloud-init"
              state=present
              create=yes
              line="exclude=cloud-init kernel"

- name: Install packages to allow for accelerated mode
  yum: name=python-keyczar  state=installed
  environment: proxy_env  

- name: Create the hosts entry.
  template: src=hosts.j2 dest=/etc/hosts

- name: copy EPEL yum repo files
  copy: src=epel.repo  dest=/etc/yum.repos.d/

- name: Create the RDO repo file
  template: src=rdo-openstack.repo.j2 dest=/etc/yum.repos.d/rdo.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Install required packages
  yum: name={{ item }} state=installed
  environment: proxy_env  
  with_items:
   - ntp
   - sudo
   - scsi-target-utils
   - dbus
   - libselinux-python
   - openssl-devel
  async: 60
  poll: 5 
  notify: restart services

- name: Disable selinux dynamically
  shell: creates=/etc/sysconfig/selinux.disabled setenforce 0 ; touch /etc/sysconfig/selinux.disabled

- name: Disable SELinux in conf file
  copy: src=selinux dest=/etc/sysconfig/selinux

- name: Disable iptables
  service: name=iptables state=stopped enabled=no

- name: Install the openstack utils packge
  yum:  name=openstack-utils state=installed
  async: 60
  poll: 5 
  environment: proxy_env

- name: setup a proxy sh init file to source
  template: src=proxy-env.sh.j2 dest=/etc/profile.d/proxy-env.sh owner=root mode=0775

- name: setup proxy environment for all users
  shell: env | grep _proxy | grep -v SUDO | sed 's/^/export /' > /etc/profile.d/proxy-env.sh
  environment: proxy_env

- include: kernel-update.yml

#- include: openvswitch-upgrade.yml


