---
# The common tasks

- name: Create the hosts entry.
  template: src=hosts.j2 dest=/etc/hosts

- name: copy EPEL yum repo files 
  copy: src=epel.repo  dest=/etc/yum.repos.d/

- name: Create the RDO repo file
  template: src=rdo-openstack.repo.j2 dest=/etc/yum.repos.d/rdo.repo
  
- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Install required packages
  yum: name={{ item }} state=installed
  with_items:
   - ntp
   - sudo
   - scsi-target-utils
   - dbus
   - libselinux-python
   - openssl-devel
  notify: restart services 
  
- name: Disable selinux dynamically
  shell: creates=/etc/sysconfig/selinux.disabled setenforce 0 ; touch /etc/sysconfig/selinux.disabled

- name: Disable SELinux in conf file
  copy: src=selinux dest=/etc/sysconfig/selinux

- name: Disable iptables
  service: name=iptables state=stopped enabled=no
 
- include: openvswitch-upgrade.yml 