##
#
# Playbook to remove aopenstack completely from all hosts
#  USE WITH CAUTION
#

- hosts: all
  tasks:

   #----------------
   # OpenStack
   #----------------

   - name: Shutdown all OpenStack services     
     service: name={{ item }} state=stopped
     ignore_errors: yes
     with_items:
       - openstack-keystone
       - openstack-glance-api
       - openstack-glance-registry
       - openstack-cinder-api      
       - openstack-nova-api
       - openstack-nova-cert
       - openstack-nova-compute
       - openstack-nova-conductor
       - openstack-nova-console
       - openstack-nova-consoleauth
       - openstack-nova-metadata-api
       - openstack-nova-novncproxy
       - openstack-nova-scheduler
       - openstack-nova-xvpvncproxy
       - neutron-dhcp-agent
       - neutron-l3-agent
       - neutron-lbaas-agent
       - neutron-metadata-agent
       - neutron-openvswitch-agent
       - neutron-ovs-cleanup
       - neutron-server
       - openstack-swift-account
       - openstack-swift-account-auditor
       - openstack-swift-account-reaper
       - openstack-swift-account-replicator
       - openstack-swift-container
       - openstack-swift-container-auditor
       - openstack-swift-container-replicator
       - openstack-swift-container-updater
       - openstack-swift-object
       - openstack-swift-object-auditor
       - openstack-swift-object-expirer
       - openstack-swift-object-replicator
       - openstack-swift-object-updater
       - openstack-swift-proxy
       - mongod 
       # - httpd
       - qpidd
       - memcached
       - nagios
       - nrpe
       - tgtd
       - iscsid

   - name: Remove all OpenStack packages
     yum: name={{ item }} state=removed
     ignore_errors: yes
     with_items:
       - openstack-ceilometer-api 
       - openstack-ceilometer-central 
       - openstack-ceilometer-collector 
       - openstack-ceilometer-common 
       - openstack-ceilometer-compute 
       - openstack-cinder-doc 
       - openstack-cinder 
       - openstack-dashboard 
       - openstack-dashboard-theme 
       - openstack-glance-doc 
       - openstack-glance 
       - openstack-heat-api-cfn 
       - openstack-heat-api-cloudwatch 
       - openstack-heat-api 
       - openstack-heat-common 
       - openstack-heat-engine 
       - openstack-keystone-doc 
       - openstack-keystone 
       - openstack-neutron-bigswitch 
       - openstack-neutron-brocade 
       - openstack-neutron-cisco 
       - openstack-neutron-hyperv 
       - openstack-neutron-linuxbridge 
       - openstack-neutron-meetering-agent 
       - openstack-neutron-mellanox 
       - openstack-neutron-metaplugin 
       - openstack-neutron-midonet 
       - openstack-neutron-ml2 
       - openstack-neutron-nec 
       - openstack-neutron-nicira 
       - openstack-neutron 
       - openstack-neutron-openvswitch 
       - openstack-neutron-plumgrid 
       - openstack-neutron-ryu 
       - openstack-neutron-vpn-agent 
       - openstack-nova-api 
       - openstack-nova-cells 
       - openstack-nova-cert 
       - openstack-nova-common 
       - openstack-nova-compute 
       - openstack-nova-conductor 
       - openstack-nova-console 
       - openstack-nova-doc 
       - openstack-nova-network 
       - openstack-nova 
       - openstack-nova-novncproxy 
       - openstack-nova-objectstore 
       - openstack-nova-scheduler 
       - openstack-nova-volume 
       - openstack-packstack 
       - openstack-quantum-cisco 
       - openstack-quantum-linuxbridge 
       - openstack-quantum-metaplugin 
       - openstack-quantum-nec 
       - openstack-quantum-nicira 
       - openstack-quantum 
       - openstack-quantum-openvswitch 
       - openstack-quantum-ryu 
       - openstack-savanna 
       - openstack-selinux 
       - openstack-swift-account 
       - openstack-swift-container 
       - openstack-swift-doc 
       - openstack-swift 
       - openstack-swift-object 
       - openstack-swift-plugin-swift3 
       - openstack-swift-proxy 
       - packstack-modules-puppet 
       - novnc 
       - python-ceilometerclient-doc 
       - python-ceilometerclient 
       - python-ceilometer 
       - python-cinderclient 
       - python-cinder 
       - python-django-horizon 
       - python-django-openstack-auth 
       - python-glanceclient-doc 
       - python-glanceclient 
       - python-heatclient-doc 
       - python-heatclient 
       - python-keystoneclient-doc 
       - python-keystoneclient 
       - python-neutronclient 
       - python-nova-adminclient 
       - python-novaclient-doc 
       - python-novaclient 
       - python-oslo-config-doc 
       - python-oslo-config 
       - python-quantumclient 
       - python-savannaclient 
       - python-swiftclient-doc 
       - python-swiftclient 
       - python-troveclient 
       - python-webob
       - python-webob1.2
       - python-webob1.0
       - python-websockify
       - python-pymongo
       - python-qpid
       - python-memcached
       - rubygem-openstack-quantum-client-doc 
       - rubygem-openstack-quantum-client 
       - mongodb-server
       - qpid-cpp-client
       - qpid-cpp-server
       - memcached
       - nagios

   - name: Remove all RDO release pkg
     yum: name=rdo-release state=removed
     ignore_errors: yes

   - name: Remove all OpenStack configs
     file: path={{ item }} state=absent
     ignore_errors: yes
     with_items:
      - /etc/keystone
      - /etc/glance
      - /etc/cinder
      - /etc/nova
      - /etc/quantum
      - /etc/neutron
      - /etc/heat
      - /etc/swift  
      - /etc/savanna    

   - name: Remove all OpenStack working dirs
     file: path={{ item }} state=absent
     ignore_errors: yes
     with_items:
      - /var/lib/keystone
      - /var/lib/cinder
      - /var/lib/glance
      - /var/lib/nova
      - /var/lib/neutron
      - /var/lib/swift
      - /var/lib/ceilometer
      - /var/log/keystone
      - /var/log/cinder
      - /var/log/glance
      - /var/log/nova
      - /var/log/neutron
      - /var/log/swift
      - /var/log/ceilometer
      - /srv/loopback-device

   - name: Install package that the followiing needs on target hosts
     yum: name=MySQL-python state=present
     ignore_errors: yes

   - name: Remove all the MySQL databases
     mysql_db: name={{ item }} state=absent
     ignore_errors: yes
     with_items:
      - keystone
      - glance
      - cinder
      - nova
      - quantum
      - neutron
      - ovs_quantum
      - ovs_neutron
      - heat
      - ceilometer     

   - name: Remove all packstack logs and settings
     file: path={{ item }} state=absent
     ignore_errors: yes
     with_items:
      - /tmp/packstack.log
      - /var/tmp/packstack
      - /tmp/packstack-answers.txt  
      - /tmp/packstack-passwords.txt       
      - /root/keystonerc_admin      

   - name: Remove any leftover userses
     user: name={{ item }} state=absent
     with_items:
      - heat
      - quantum
      - neutron
      - swift
      - nova
      - ceilometer
      - keystone
      - cinder
      - glance
      - savanna

   - name: remove associated groupses
     group: name={{ item }} state=absent
     with_items:
      - heat     
      - quantum
      - neutron
      - swift
      - nova
      - ceilometer
      - keystone
      - cinder
      - glance
      - savanna

   - name: unmount swift loopback devices
     shell: df -h | grep "/srv/loopback-device/device" | awk '{print $1}' | xargs -ixxx umount xxx

   #----------------
   # MySQL
   #----------------

   - name: Remove MySQL
     yum: name={{ item }} state=removed
     ignore_errors: yes
     with_items:
      - mysql-server
      - mysql  

   - name: Remove remaining vestiges of MySQL
     file: path={{ item }} state=absent
     ignore_errors: yes
     with_items:
      - /var/lib/mysql
      - /etc/mysql
      - /etc/my.cnf
      - /root/.my.cnf

   - name: Remove remaining vestiges of other settings
     file: path={{ item }} state=absent
     ignore_errors: yes
     with_items:
      - /etc/profile.d/http_proxy.sh
      - /etc/profile.d/proxy-env.sh      

    #------------------
    # GLUSTER
    #------------------

   - name: unmount all glusterfs mounts
     command: umount /mnt/gv-{{ item }}
     with_items: [cinder, nova, swift]
     ignore_errors: yes
#     mount: name=/mnt/gv0 state=unmounted fstype=gluster 

   - name: unmount all glusterfs test mounts
     command: umount /gluster-test-mnt 
     ignore_errors: yes
#     mount: name=/mnt/gv0 state=unmounted fstype=gluster 

   - name: Shutdown gluster volume
     shell: echo "y" | gluster volume stop {{ item }} force 
     with_items: [cinder, nova, swift]
     ignore_errors: yes

   - name: Delete gluster volume
     shell: echo "y" | gluster volume delete {{ item }}
     with_items: [cinder, nova, swift]
     ignore_errors: yes

   - name: Shutdown all gluster services
     service: name={{ item }} state=stopped
     ignore_errors: yes
     with_items:
       - glusterd
       - glusterfsd

   - name: Clear out any remaining gluster processes
     shell: pkill glusterfsd
     ignore_errors: yes

   - name: Clear out any remaining glusterfs processes
     shell: pkill glusterfs
     ignore_errors: yes

   - name: Clear out any remaining glusterd processes
     shell: pkill glusterd
     ignore_errors: yes

#
# Clean brick to be used with gluster
#
   - name: copy over brick cleanup shell script
     copy: src=../roles/gluster/files/clear-gluster-xattr.sh  dest=/tmp/clear-gluster-xattr.sh owner=root group=root mode=0755

   - name: install attr package
     yum: name={{ item }} state=installed
     with_items: [which, attr]

   - name: clear out any xattributes on cany bricks if used before ...
     shell: /tmp/clear-gluster-xattr.sh /export/{{ item }}-brick
     with_items: [cinder, nova, swift]
     ignore_errors: yes

   - name: unmount all xfs mounts used by gluster
     command: umount /export/{{ item }}-brick
     with_items: [cinder, nova, swift]
     ignore_errors: yes

   - name: remove all loopback devices not mounted
     shell: "losetup -a | awk -F: '{print $1}' | xargs -ixxx losetup -d xxx "
     ignore_errors: yes

   - name: Remove all gluster packages
     yum: name={{ item }} state=removed
     ignore_errors: yes
     with_items:
      - glusterfs-server
      - glusterfs-fuse
      - glusterfs

   - name: Remove gluster logs and state dir
     file: path={{ item }} state=absent
     ignore_errors: yes
     with_items:
      - /var/lib/glusterd
      - /var/log/glusterd

    #------------------
    # LibVirt
    #------------------

   - name: destroy running instances
     shell: virsh list  | grep "^[0-9]" | awk '{print $1}' | xargs -ixxx virsh destroy  xxx
     ignore_errors: yes

   - name: Shutdown all OpenStack services     
     service: name={{ item }} state=stopped
     ignore_errors: yes
     with_items:
       - libvirt-guests
       - libvirtd

   - name: Remove all libvirt packages
     yum: name={{ item }} state=removed
     ignore_errors: yes
     with_items:
       - libvirt

   - name: Clear out libvirt data and logs
     file: path={{ item }} state=absent
     ignore_errors: yes
     with_items:
      - /var/lib/libvirt 
      - /var/log/libvirt

   #-------------------------
   # OpenVSwitch & Bridging
   #-------------------------

   - name: clear out OpenVSwitch ports
     shell: ovs-vsctl list-ports {{ item }} | xargs -ixxx ovs-vsctl del-port {{ item }} xxx
     ignore_errors: yes 
     with_items:
      - br-ex
      - br-int
      - br-tun
     tags: debug

   - name: clear out OpenVSwitch bridges
     shell: ovs-vsctl del-br {{ item }}
     ignore_errors: yes 
     with_items:
      - br-ex
      - br-int
      - br-tun
      - undef
     tags: debug

   - name: remove any generated linux-bridge interfaces
     shell: >
              BS=$(brctl show | grep qbr | awk '{print $1}' );  
              for B in $BS; do  
                IS=$( brctl show $B | awk '{print $4}' | grep qvb );
                for I in $IS; do brctl delif $B $IF; done
                ifconfig $B down; 
                brctl delbr $B; 
              done
     tags: debug

   - name: remove any generated interfaces reported by ifconfig
     shell: ifconfig | grep "^q" | awk '{print $1}' | xargs -ixxx ifconfig xxx down 

   - name: remove any errant processes
     shell: pkill {{ item }}
     with_items:
      - dnsmasq
     ignore_errors: yes      
     tags: debug

   - name: shutdown OpenVSwitch
     service: name=openvswitch state=stopped
     ignore_errors: yes   

   - name: remove openvswitch
     yum: name=openvswitch state=absent

   - name: Clear out openvswitch data and logs
     file: path={{ item }} state=absent
     ignore_errors: yes
     with_items:
      - /etc/openvswitch
      - /var/lib/openvswitch
      - /var/log/openvswitch

   - name: remove neutron-related kernel modules 
     shell: modprobe -r {{ item }}
     with_items:
      - openvswitch
      - vxlan
      - vhost_net
     ignore_errors: yes      
     tags: debug

   - name: restart iptables
     service: name=iptables state=restarted

     #
     # Finally last ditch killing of offending processes
     #

   - name: Kill off errant process
     shell: pkill {{ item }}
     with_items: [glusterfs, qemu-kvm, dnsmasq]
     ignore_errors: yes 
